# Site settings
title: SauerSauce
email: sauersauce.contact@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to learn and share Sauerbraten's world
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sauer-sauce.github.io" # the base hostname & protocol for your site
twitter_username: SalatielSauer
github_username:  SauerSauce

# Build settings
markdown: kramdown